### ISSUE TITLE
[ADR] Data submission schema strategy

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/ccf-app-samples#101]
We have 3 strategies to choose. We better provide an ADR for these options:

1. Fully flexible data ingestion (data + schema at the request), trade off: Reporting
2. Semi-flexbile data ingestion (data is submitted for registered schema, trade off: schema registration requires data reset)
3. Defined data ingestion (data is submitted by the scheme contract, trade off: operational playbook, data reset)

Current requirements is towards having a scheme ahead of time (closer to option 3)

**Comment by macromania** [comment]
ADR 
- explain the decision #36 
- alternatives can be explained lightly
- more detailed alternatives can be in the backlog
