### ISSUE TITLE
Enhance E2E Test Scripts

### ISSUE THREAD

**Issue by mkcomer** [microsoft/ccf-app-samples#120]
Follow on story to https://github.com/orgs/microsoft/projects/542/views/1.

Enhance E2E testing scripts, edge cases and more thorough check on returned summary object for reporting.

## Acceptance Criteria 
- [ ] Enhanced scripts added to repo. 
- [ ] Check that a particular key is IN_CONSENSUS, NOT_ENOUGH_DATA, LACK_OF_CONSENSUS
- [x] Join the E2E and the Demo scripts together and have the ability to run the Demo in a headless mode so it can be part of CI - #144

**Comment by ross-p-smith** [comment]
We have a generic ./scripts/test_sandbox.sh which starts the network and is used for all samples and this in turn calls ./data-reconciliation-app/test/test.sh which runs the test for that sample - so starting the network is done for you
