### ISSUE TITLE
SUGGESTION: Add Link to CCP In README.md

### ISSUE THREAD

**Issue by martinpeck** [microsoft/ccf-app-samples#125]
README.md starts with this text...

> Sample applications for the Confidential Consortium Framework (CCF).

... but doesn't link to any definition of what CCF might be. 

Assuming the following link is the best/correct one to use, it might be a good idea to add this link to the README...

https://www.microsoft.com/en-us/research/project/confidential-consortium-framework/

If this makes sense, I'm happy to raise a very small PR to add this link to the README

**Comment by martinpeck** [comment]
if there's a better link to use, then happy to PR that link into the README instead.

e.g. are any of these more appropriate...?

- https://github.com/microsoft/CCF
- https://ccf.microsoft.com/

**Comment by ross-p-smith** [comment]
Thanks for the those Martin - happily accept any more if you find any!! :-)
