### ISSUE TITLE
Improve e2e Testing Host Start/Stop

### ISSUE THREAD

**Issue by macromania** [microsoft/ccf-app-samples#142]
In e2e testing, we kill the host using:

```
execSync('kill -9 $(pgrep python)');
```

Is there a nicer way to do this than killing python? Will you not have the shell script still running in a broken state?

**Comment by ross-p-smith** [comment]
In the current (not saying it is right) demo/test we have a wrapper script that is responsible for starting the host (sandbox/docker/mccf) and then that calls test. There is then a trap within the wrapper script that either shuts the sandbox, stops docker or do nothing in the case of mccf. Maybe this isn't an issue if we keep this?

**Comment by ross-p-smith** [comment]
I don't believe it is the responsibility of the test themselves to start/stop the host
