### ISSUE TITLE
Using CSV for e2e testing

### ISSUE THREAD

**Issue by macromania** [microsoft/ccf-app-samples#143]
Instead of https://github.com/microsoft/ccf-app-samples/pull/136/files/8b3ddb5b7eb1588e91db7f5c0753af42cd9493e2#diff-67f8501e571bc3ec8f4bacfaf921ca979258f1a032ad1eed2cc660a34c58d960, we can just use CSV.

Implementing this would be better after #131

**Comment by ross-p-smith** [comment]
We will close this issue as it relates to a PR that has since been closed
