### ISSUE TITLE
Move Data Recon App Deployment (CD) to CCF Subscription

### ISSUE THREAD

**Issue by mkcomer** [microsoft/ccf-app-samples#150]
Amaury has confirmed there is a CCF subscription that they use for CI (and various other purposes), we can repoint CD to theirs. 

Reach out to Amaury for details on the subscription or host a pairing session to move our CD data recon to deploy to their CCF subscription.

Test demo in CCF subscription

# Acceptance Criteria
- Update CD to deploy data recon to mCCF in CCF subscription
- Run Test/Demo to ensure we are good for the demo

**Comment by takuro-sato** [comment]
It's now under CCF subscription
