### ISSUE TITLE
Make test.sh idempotent

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/ccf-app-samples#17]
At the moment, running ./banking-app/test.sh only works the first time as it relies on a bank account balance which always increases.

Update the test so that you can run it multiple times.

**Comment by takuro-sato** [comment]
`./banking-app/test.sh` creates a new sandbox each time. So, I think it can already run multiple time.

**Comment by ross-p-smith** [comment]
Ah!!! I understand. I should have stopped my previous sandbox and run the tests as an isolated step! I'll add a sentence into the readme
