### ISSUE TITLE
Followup with CCF team on Deploying extra openAPI document attributes as part of the app bundle (securitySchemes - Document Info)

### ISSUE THREAD

**Issue by Aymalla** [microsoft/ccf-app-samples#185]
Currently, a custom OpenApi document is created for our application instead of using the built-in endpoint (/app/api), because it lacks some attributes like:
- SecuritySchemes 
- Document Information
- Endpoints description

There is a suggestion to deploy extra openAPI document attributes as part of the app bundle, and if it is implemented by the CCF Team, the custom document implementation should be deprecated and replaced by the built-in one (/app/api).

# Acceptance Criteria 
- [ ] Add issue in CCF repo

**Comment by ross-p-smith** [comment]
Closing this as it is now referenced in https://github.com/microsoft/CCF/issues/4947
