### ISSUE TITLE
Documentation for decentralized-rbac app is a bit incomplete

### ISSUE THREAD

**Issue by all-seeing-code** [microsoft/ccf-app-samples#246]
Some related issues which I faced when trying to run the application locally in a dev container.

1. del-cli is not pre-installed which means couldn't run npm run build out of the box in the dev container as mentioned in the docs.
2. No Makefile. Unlike other applications, this one doesn't have a make file which makes it a little painful to run the application. I had to figure out the correct command: `/opt/ccf_virtual/bin/sandbox.sh --js-app-bundle ./dist/` to start the application.
3. The GET/POST requests valid for the application are missing from the README.md.

I don't expect or require a fix for this issue but keeping it here as an issue log.

**Comment by achamayou** [comment]
@all-seeing-code it looks like `del-cli` is listed in dev dependencies though: https://github.com/microsoft/ccf-app-samples/blob/main/decentralize-rbac-app/package.json#L45, I am not extremely familiar with npm but it seems to me that you would expect to install devDependencies before being able to do a `run build`?
