### ISSUE TITLE
Deploy SGX VM via IaC and run sample app

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/ccf-app-samples#35]
We should have a simple way of building a VM in Azure and deploy the sample application to it so we can show customers how to deploy it to Azure

**Feedback/Context from PG:** 

There is some value in this story. 
- This may be useful for a developer to understand how to get a single node, CCF network app to run on Infrastructure; however, this is not how most will set up their networks in production environments
- This may also be useful to run performance testing on deployed/running sample app.
- Useful to get someone started 
- In reality, SGX is not the easiest VM for any dev to create (limited to certain regions, very expensive). Suggested that we leverage any D.C Intel VM for this story. 

- **What may be "More Useful"and provide more value** is taking a sample app CCF app here and deploying it to Azure leveraging mCCF ARM templates + documenting that workflow for a developer (more realistic use case than VM)
- Recommend we get access to mCCF first, as this ticket can provide more value once we have an idea of ARM templates/mCCF world

**Comment by takuro-sato** [comment]
What is PG?

**Comment by ross-p-smith** [comment]
PG is the Product Group - I suppose you fit into that! :-)
