### ISSUE TITLE
Add the forum app

### ISSUE THREAD

**Issue by takuro-sato** [microsoft/ccf-app-samples#4]
Suggested by @heidihoward .
It was originally in [CCF/samples/apps/forum at 7455dd869df4996d267af228d17a484a33cd67c7 · microsoft/CCF (github.com)](https://github.com/microsoft/CCF/tree/7455dd869df4996d267af228d17a484a33cd67c7/samples/apps/forum).

Maybe it doesn't highest priority, but it's worth to consider.

**Comment by achamayou** [comment]
Resolved by the inclusion of the more generic successor to the forum app, the data reconciliation app: https://github.com/microsoft/ccf-app-samples/tree/main/data-reconciliation-app
