### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by takuro-sato** [microsoft/ccf-app-samples#6]
## Short term goal
- Run tests with the virtual TEE environment.

## Long term goal
- Run tests with actual SGX or SEV-SNP

## Tool
GitHub Actions should be enough.

**Comment by takuro-sato** [comment]
CI with virtual TEE was addressed in #19

**Comment by ross-p-smith** [comment]
@takuro-sato - do you think we should close this one as we have CI in a virtual and CD in a SGX?

**Comment by takuro-sato** [comment]
Agree. Thank you for pointing it out
