### ISSUE TITLE
Design data reporting APIs

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/ccf-app-samples#85]
Design Data Reporting - API, Service & Repository Layers.

Requirements: https://github.com/microsoft/ccf-app-samples/blob/main/data-reconciliation-app/docs/data-schema-data-flow.md#data-reporting

Members will query for report summary. All data returned will be JSON. Voting Threshold should be configurable. 

Design APIs:
- [x] by individual record (unique ID)
- [x] for ALL data 

Design Service Layer
- [x] Design returned summary object. Table: https://github.com/microsoft/ccf-app-samples/blob/main/data-reconciliation-app/docs/data-schema-data-flow.md#data-results-schema. Summary object can be used for both APIs.
- [x] Pseudo Code: how we will manipulate the domain model (K-V store) and create summary object?

Repository Layer: 
- Query K-V store by ID
- Query K-V store for ALL

Acceptance Criteria:
1. ADR 
2. Review ADR with team (Sync or Async)

**Comment by macromania** [comment]
All the api design and service layer connections are implemented on this branch: https://github.com/microsoft/ccf-app-samples/commits/canga/85-data-reporting-api

Remaining work is to 

1. implement this ADR: https://github.com/microsoft/ccf-app-samples/blob/main/data-reconciliation-app/docs/adr/03-reconciliation-logic.md
2. Unit testing the domain model
3. Updating demo scripts to have e2e integration testing using `curl`

**Comment by macromania** [comment]
I'm closing this issue and remaining work will be tracked on #86
